import React from 'react'
import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
    title: "Spewpa | A Text-to-Image Generation Platform.",
    description: "Generated by create next app",
};

const RootLayout = ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {
    return (
        <html lang="en">
            <body>
                {children}
            </body>
        </html>
    )
}

export default RootLayout
